<project><modelVersion>4.0.0</modelVersion><groupId>pt.demo</groupId><artifactId>my-auth-spi</artifactId><version>0.1</version>
<dependencies><dependency><groupId>org.keycloak</groupId><artifactId>keycloak-server-spi</artifactId><version>26.0.5</version><scope>provided</scope></dependency></dependencies></project>
