<project><modelVersion>4.0.0</modelVersion>
<parent><groupId>pt.demo</groupId><artifactId>platform</artifactId><version>1.0</version></parent>
<artifactId>inventory</artifactId>
<dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
<dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId></dependency></dependencies>
<build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build>
</project>
